apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alfio
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alfio
    spec:
      containers:
      - name: alfio-app
        image: alfio/alf.io
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: jdbc-session
        - name: POSTGRES_PORT_5432_TCP_PORT
          value: "5432"
        - name: POSTGRES_ENV_POSTGRES_DB
          value: alfio
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: "127.0.0.1"
        - name: POSTGRES_ENV_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: alfio-postgresql-credentials
              key: username
        - name: POSTGRES_ENV_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alfio-postgresql-credentials
              key: password
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseConcMarkSweepGC -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: web
        livenessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 180
